name: Voy
options:
  bundleIdPrefix: com.yannickherrero
  deploymentTarget:
    iOS: "18.0"
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "6.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
targets:
  Voy:
    type: application
    platform: iOS
    sources:
      - path: Voy
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yannickherrero.voy
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: Voy
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        SUPPORTS_MACCATALYST: false
    scheme:
      testTargets: []
